pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Seth Hendrick
title: Rochester Longboarding Info
description: "Places to Longboard in Rochester, NY"
url: https://www.roclongboarding.info
urlnohttp: www.roclongboarding.info
contact: contact@roclongboarding.info
github: https://github.com/xforever1313/roclongboarding.info
githubissues: https://github.com/xforever1313/roclongboarding.info/issues

disqus_shortname: roclongboarding-info

# ActivtyPub:
actpub_directory: "activitypub"
actpub_outbox: true
actpub_inbox: true
actpub_profileurl: posts.html
actpub_username: posts
actpub_icon: "https://www.roclongboarding.info/static/favicons/favicon-310.png"
actpub_created: "2020-09-07T00:00:00.0000000Z"
actpub_summary: "I post whenever there's a new post on Rochester Longboarding Info, the site about places to Longboard in Rochester, NY."
actpub_publickeyfile: "activitypub/public.pem"
actpub_following:
 - "@xforever1313@tech.lgbt"

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - cake.config
 - .cake
 - tools
 - Readme.md
