pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Seth Hendrick
title: Rochester Longboarding Info
url: https://www.roclongboarding.info
contact: contact@roclongboardin.info
github: https://github.com/xforever1313/roclongboarding.info

disqus_shortname: roclongboarding-info

exclude:
 - .gitignore
 - .git
 - .vs
 - .vscode
 - build.cake
 - tools
