pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Seth Hendrick
title: Rochester Longboarding Info
description: "Places to Longboard in Rochester, NY"
url: https://www.roclongboarding.info
urlnohttp: www.roclongboarding.info
contact: contact@roclongboarding.info
github: https://github.com/xforever1313/roclongboarding.info
githubissues: https://github.com/xforever1313/roclongboarding.info/issues

disqus_shortname: roclongboarding-info

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - Readme.md
